#!/usr/bin/python3

import pathlib
import shutil
import subprocess

for theme in ['dark','light'] :
  icon_theme_root = "/usr/share/icons/ubuntu-mono-{0}/".format(theme)
  subprocess.check_call("gtk-update-icon-cache "+ icon_theme_root, shell=True)
